import { motion } from 'framer-motion';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

const Page: NextPage = () => {
  const [count, setCount] = useState<number>(10);

  const transition = { duration: 0.5, ease: [0.43, 0.13, 0.23, 0.96] };

  const thumbnailVariants = {
    initial: { scale: 0.9, opacity: 0 },
    enter: { scale: 1, opacity: 1, transition },
    exit: {
      scale: 0.5,
      opacity: 0,
      transition: { ...transition, duration: 1 },
    },
  };

  const frameVariants = {
    hover: { scale: 0.95 },
  };

  const imageVariants = {
    hover: { scale: 1.1 },
  };

  return (
    <motion.div
      initial={{ x: 1500 }}
      animate={{ x: 0 }}
      exit={{ x: -1500 }}
      transition={{ duration: 1, times: [0, 0.2, 1] }}
    >
      <Head>
        <title>5S活動発表</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex w-full'>
        <Link href={'/' + (count - 1)}>
          <a className='flex items-center h-screen text-9xl text-blue-400 bg-slate-100'>◂</a>
        </Link>
        <main className='flex items-center w-full h-screen bg-slate-100'>
          <motion.div variants={thumbnailVariants} className='m-auto w-full'>
            <motion.div className='mb-20 text-7xl text-center'>１．取り組み状況</motion.div>
            <motion.ul className='m-auto w-5/6 list-disc' variants={thumbnailVariants}>
              <motion.li
                className='my-10 text-5xl '
                initial='initial'
                animate='enter'
                exit='exit'
                whileHover={{
                  scale: 1.1,
                  transition: { duration: 0.5 },
                }}
                variants={thumbnailVariants}
                transition={transition}
              >
                <Link href={'/' + (count + 1)}>
                  <a> 活動が計画的に行われ、職制と対話して進めているか</a>
                </Link>
              </motion.li>
              <motion.li
                className='my-10 text-5xl '
                initial='initial'
                animate='enter'
                exit='exit'
                whileHover={{
                  scale: 1.1,
                  transition: { duration: 0.5 },
                }}
                variants={thumbnailVariants}
                transition={transition}
              >
                リーダーが定期的にパトロールし、自ら進んで5S活動を行っている
              </motion.li>
              <motion.li
                className='my-10 text-5xl '
                initial='initial'
                animate='enter'
                exit='exit'
                whileHover={{
                  scale: 1.1,
                  transition: { duration: 0.5 },
                }}
                variants={thumbnailVariants}
                transition={transition}
              >
                職場規律やルールを維持する枠割分担を決めてある（5S責任者の権限）
              </motion.li>
              <motion.li
                className='my-10 text-5xl '
                initial='initial'
                animate='enter'
                exit='exit'
                whileHover={{
                  scale: 1.1,
                  transition: { duration: 0.5 },
                }}
                variants={thumbnailVariants}
                transition={transition}
              >
                主旨を全員が理解し分担しているか
              </motion.li>
            </motion.ul>
          </motion.div>
        </main>
        <Link href={'/' + (count + 1)}>
          <a className='flex right-0 items-center h-screen text-9xl text-blue-400 bg-slate-100'>
            ▸
          </a>
        </Link>
      </div>
    </motion.div>
  );
};

export default Page;
