import { motion } from 'framer-motion';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

const Page: NextPage = () => {
  const [count, setCount] = useState<number>(2);

  const delay = {
    visible: { opacity: 1 },
    hidden: { opacity: 0 },
  };

  return (
    <motion.div
      initial={{ x: 1500 }}
      animate={{ x: 0 }}
      exit={{ x: -1500 }}
      transition={{ duration: 1, times: [0, 0.2, 1] }}
    >
      <Head>
        <title>5S活動発表</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex w-full'>
        <Link href={'/' + (count - 1)}>
          <a className='flex items-center h-screen text-9xl text-blue-400 bg-slate-100'>◂</a>
        </Link>
        <main className='flex items-center w-full h-screen bg-slate-100'>
          <div className='m-auto text-center'>
            <div className='text-6xl'>銀賞獲得の為には</div>
            <div className='my-10 text-9xl'>銅賞水準の維持</div>
            <motion.div
              className='text-6xl'
              variants={delay}
              transition={{ ease: 'easeIn', delay: 2, duration: 2 }}
              initial='hidden'
              animate='visible'
            >
              に加えて次の項目が必要
            </motion.div>
          </div>
        </main>
        <Link href={'/' + (count + 1)}>
          <a className='flex right-0 items-center h-screen text-9xl text-blue-400 bg-slate-100'>
            ▸
          </a>
        </Link>
      </div>
    </motion.div>
  );
};

export default Page;
