import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function About() {
  return (
    <>
      <Head>
        <title>5S活動発表</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center h-screen bg-slate-100'>
        <div className='m-auto text-center'>
          <div className='text-6xl'>今年度の目標</div>
          <div className='my-4 text-9xl'>＜銀賞の獲得＞</div>
          <Link href={'/' + 1}>
            <a className='text-9xl text-blue-400'>➡</a>
          </Link>
        </div>
      </main>
    </>
  );
}
